// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace EpiServer.AlloyDemo.GraphAPI.Business.Parking
{

    public class ParkingStatus
    {

        [JsonProperty("availableCapacity")]
        public int AvailableCapacity { get; set; }

        [JsonProperty("totalCapacity")]
        public int TotalCapacity { get; set; }

        [JsonProperty("open")]
        public bool Open { get; set; }

        [JsonProperty("suggestedCapacity")]
        public string SuggestedCapacity { get; set; }

        [JsonProperty("activeRoute")]
        public string ActiveRoute { get; set; }

        [JsonProperty("lastModifiedDate")]
        public string LastModifiedDate { get; set; }
    }

}
